name: Release Tag
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 버전 정보 추출
      run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,4}\.[0-9]{1,2}\.[0-9]{1,2}')"
      id: extract_version_name

    # - name: Build Changelog
    #     id: github_release
    #     uses: mikepenz/release-changelog-builder-action@v1
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Create release
      uses: actions/github-script@v4.0.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.request(`POST /repos/${{ github.repository }}/releases`, {
            tag_name: "${{ steps.extract_version_name.outputs.version }}",
            name: "${{ steps.extract_version_name.outputs.version }}",
            generate_release_notes: true
          });

    # - name: Release 생성
    #   uses: actions/create-release@v1
    #   env: 
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with: 
    #     tag_name: ${{ steps.extract_version_name.outputs.version }} 
    #     release_name: ${{ steps.extract_version_name.outputs.version }}
    #     body: ${{steps.github_release.outputs.changelog}}
